import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Global/NavBar/Navbar";
import StoreProvider from "./StoreProviders";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import '@ant-design/v5-patch-for-react-19';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const infoData = await GetInfoForCustomer();

  return (
    <StoreProvider>

    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fixed lg:relative z-40 bg-white w-full">
          <Navbar  />
        </div>
        {children}
      </body>
    </html>
    </StoreProvider>
    
  );
}
